services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=MySQL08022000
    ports:
      - 3307:3306
    volumes:
          - ./:/docker-entrypoint-initdb.d
          - db:/var/lib/mysql
          
volumes:
    db:
      driver: local
        
    
